name: Test changes
on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - main
      - staging
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm test
